name: flutter_cache_manager_hive
description: flutter_cache_manager implementation for hive.
version: 0.0.7
homepage: https://github.com/vishna/flutter_cache_manager_hive

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.4.1
  hive: ^1.4.1+1
  path_provider: "^1.4.0"
  uuid:  "^2.0.2"
  http: "^0.12.0+2"
  path: "^1.6.4"
  pedantic: "^1.8.0+1"
  clock: ^1.0.1
  file: ^5.1.0
  rxdart: '>=0.23.1 <0.25.0'
  meta: ^1.1.8